# Generated by Django 5.1.6 on 2025-05-16 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprehensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Known', 'Not Known')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveEyeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('left_eye_score', models.FloatField()),
                ('right_eye_score', models.FloatField()),
                ('additional_ocular_complaints', models.BooleanField(default=False)),
                ('test_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMedicalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('medical_treatment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Known', 'Not Known')], max_length=10)),
                ('medicine', models.CharField(max_length=50)),
                ('treatment_eye', models.CharField(choices=[('Right_eye', 'Right_eye'), ('Left_eye', 'Left_eye'), ('Both', 'Both'), ('Systemic', 'Systemic')], max_length=50)),
                ('medicine_type', models.CharField(choices=[('Eye drop', 'Eye drop'), ('Eye ointment', 'Eye ointment'), ('Injection', 'Injection'), ('capsule', 'capsule'), ('tablet', 'tablet'), ('Syrup', 'Syrup'), ('spray', 'spray')], max_length=50)),
                ('times_per_day', models.IntegerField(choices=[(1, 'one time a day'), (2, 'twice a day'), (3, 'three times a day'), (4, 'four times a day'), (5, 'five times a day')])),
                ('prescribed_date', models.DateField()),
                ('current_medical_treatment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_management', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20)),
                ('frame_choice', models.CharField(blank=True, max_length=50, null=True)),
                ('glasses_ordered', models.BooleanField(default=False)),
                ('glasses_ready', models.BooleanField(default=False)),
                ('glasses_received', models.BooleanField(default=False)),
                ('glasses_dispensed', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('dispensing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('Hypertension', models.BooleanField(default=False)),
                ('Diabetes', models.BooleanField(default=False)),
                ('Cataract', models.BooleanField(default=False)),
                ('Glaucoma', models.BooleanField(default=False)),
                ('Other_glasses', models.BooleanField(default=False)),
                ('Other', models.BooleanField(default=False)),
                ('none', models.BooleanField(default=False)),
                ('relationshipwithchild', models.CharField(choices=[('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother')], max_length=50)),
                ('search_term', models.CharField(blank=True, max_length=100, null=True)),
                ('family_history', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firstscreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('wears_spectacles', models.CharField(blank=True, choices=[('Has spectacles and is currently wearing them', 'Has spectacles and is currently wearing them'), ('Has spectacles but not wearing them', 'Has spectacles but not wearing them'), ('Does not wear spectacles', 'Does not wear spectacles'), ('Has spectacles but not wearing however has them in their possession', 'Has spectacles but not wearing however has them in their possession'), ('Has spectacles but not wearing and not in their possession', 'Has spectacles but not wearing and not in their possession'), ('Has previously worn spectacles but no longer has spectacles', 'Has previously worn spectacles but no longer has spectacles'), ('Has never worn spectacles before', 'Has never worn spectacles before')], max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_clinic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitialEyeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('test_type', models.CharField(default='Snellen E Chart', max_length=50)),
                ('left_eye_score', models.FloatField()),
                ('right_eye_score', models.FloatField()),
                ('test_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OtherMedicalIssueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('medical_issue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('other_medical_issues', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, unique=True)),
                ('first_screening', models.BooleanField(default=False)),
                ('second_screening', models.BooleanField(default=False)),
                ('comprehensive_eye_exam', models.BooleanField(default=False)),
                ('measure_visual_acuity', models.BooleanField(default=False)),
                ('diagnosis_management', models.BooleanField(default=False)),
                ('dispensing', models.BooleanField(default=False)),
                ('spectacle_wearing_history', models.BooleanField(default=False)),
                ('family_history', models.BooleanField(default=False)),
                ('surgery_treatment_history', models.BooleanField(default=False)),
                ('current_medical_treatment', models.BooleanField(default=False)),
                ('refraction_spectacle_presentation', models.BooleanField(default=False)),
                ('other_medical_issues', models.BooleanField(default=False)),
                ('refraction_and_examination', models.BooleanField(default=False)),
                ('surgery_history', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_complaint', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefractionExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('chief_complaint', models.CharField(choices=[('NO_COMPLAINTS', 'No Complaints'), ('ITCHING', 'Itching of eye/s'), ('HEADACHE', 'Headaches'), ('WATERING', 'Watering of eye/s'), ('REDNESS', 'Redness of eye/s'), ('BLURRING', 'Blurring of vision'), ('PAIN', 'Pain in eye/s'), ('DISCHARGE', 'Discharge from eye/s'), ('EYE_STRAIN', 'Eye strain'), ('SWELLING', 'Swelling of eye/s'), ('IRRITATION', 'Irritation of eye/s'), ('INJURY', 'Injury to eye/s'), ('FOREIGN_BODY', 'Foreign body in eye/s'), ('PHOTOPHOBIA', 'Photophobia'), ('DIPLOPIA', 'Diplopia'), ('POLYOPIA', 'Polyopia'), ('DROOPING_LID', 'Drooping of lid/s'), ('SQUINT', 'Squint'), ('SQUEEZING_EYE', 'Squeezing eye'), ('ABNORMAL_HEAD_POSTURE', 'Abnormal head posture'), ('FLOATERS', 'Floaters/black spots'), ('FLASHES', 'Flashes of light')], max_length=255)),
                ('eye', models.CharField(choices=[('LEFT EYE', 'Left Eye'), ('RIGHT EYE', 'Right Eye'), ('BOTH EYES', 'Both Eyes')], max_length=10)),
                ('duration', models.IntegerField()),
                ('additional_ocular_complaint', models.BooleanField(default=False)),
                ('ocular_alignment_remarks', models.TextField(blank=True, null=True)),
                ('refraction_and_examination', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefractionSpectacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('spherical_prescription_re', models.CharField(blank=True, choices=[('0.00', '0.00'), ('+0.25', '+0.25'), ('+0.50', '+0.50'), ('+0.75', '+0.75'), ('+1.00', '+1.00'), ('+1.25', '+1.25'), ('+1.50', '+1.50'), ('+1.75', '+1.75'), ('+2.00', '+2.00'), ('+2.25', '+2.25'), ('+2.50', '+2.50'), ('+2.75', '+2.75'), ('+3.00', '+3.00'), ('+3.25', '+3.25'), ('+3.50', '+3.50'), ('+3.75', '+3.75'), ('+4.00', '+4.00'), ('+4.25', '+4.25'), ('+4.50', '+4.50'), ('+4.75', '+4.75'), ('+5.00', '+5.00'), ('+5.25', '+5.25'), ('+5.50', '+5.50'), ('+5.75', '+5.75'), ('+6.00', '+6.00'), ('+6.50', '+6.50'), ('+7.00', '+7.00'), ('+7.50', '+7.50'), ('+8.00', '+8.00'), ('+8.50', '+8.50'), ('+9.00', '+9.00'), ('+9.50', '+9.50'), ('+10.00', '+10.00'), ('+10.50', '+10.50'), ('+11.00', '+11.00'), ('+11.50', '+11.50'), ('+12.00', '+12.00'), ('+12.50', '+12.50'), ('+13.00', '+13.00'), ('+13.50', '+13.50'), ('+14.00', '+14.00'), ('+14.50', '+14.50'), ('+15.00', '+15.00'), ('+15.50', '+15.50'), ('+16.00', '+16.00'), ('+16.50', '+16.50'), ('+17.00', '+17.00'), ('+17.50', '+17.50'), ('+18.00', '+18.00'), ('+18.50', '+18.50'), ('+19.00', '+19.00'), ('+19.50', '+19.50'), ('+20.00', '+20.00'), ('-0.25', '-0.25'), ('-0.50', '-0.50'), ('-0.75', '-0.75'), ('-1.00', '-1.00'), ('-1.25', '-1.25'), ('-1.50', '-1.50'), ('-1.75', '-1.75'), ('-2.00', '-2.00'), ('-2.25', '-2.25'), ('-2.50', '-2.50'), ('-2.75', '-2.75'), ('-3.00', '-3.00'), ('-3.25', '-3.25'), ('-3.50', '-3.50'), ('-3.75', '-3.75'), ('-4.00', '-4.00'), ('-4.25', '-4.25'), ('-4.50', '-4.50'), ('-4.75', '-4.75'), ('-5.00', '-5.00'), ('-5.25', '-5.25'), ('-5.50', '-5.50'), ('-5.75', '-5.75'), ('-6.00', '-6.00'), ('-6.50', '-6.50'), ('-7.00', '-7.00'), ('-7.50', '-7.50'), ('-8.00', '-8.00'), ('-8.50', '-8.50'), ('-9.00', '-9.00'), ('-9.50', '-9.50'), ('-10.00', '-10.00'), ('-10.50', '-10.50'), ('-11.00', '-11.00'), ('-11.50', '-11.50'), ('-12.00', '-12.00'), ('-12.50', '-12.50'), ('-13.00', '-13.00'), ('-13.50', '-13.50'), ('-14.00', '-14.00'), ('-14.50', '-14.50'), ('-15.00', '-15.00'), ('-15.50', '-15.50'), ('-16.00', '-16.00'), ('-16.50', '-16.50'), ('-17.00', '-17.00'), ('-17.50', '-17.50'), ('-18.00', '-18.00'), ('-18.50', '-18.50'), ('-19.00', '-19.00'), ('-19.50', '-19.50'), ('-20.00', '-20.00')], max_length=50, null=True)),
                ('cylindrical_prescription_re', models.CharField(blank=True, choices=[('0.00', '0.00'), ('+0.25', '+0.25'), ('+0.50', '+0.50'), ('+0.75', '+0.75'), ('+1.00', '+1.00'), ('+1.25', '+1.25'), ('+1.50', '+1.50'), ('+1.75', '+1.75'), ('+2.00', '+2.00'), ('+2.25', '+2.25'), ('+2.50', '+2.50'), ('+2.75', '+2.75'), ('+3.00', '+3.00'), ('+3.25', '+3.25'), ('+3.50', '+3.50'), ('+3.75', '+3.75'), ('+4.00', '+4.00'), ('+4.25', '+4.25'), ('+4.50', '+4.50'), ('+4.75', '+4.75'), ('+5.00', '+5.00'), ('+5.25', '+5.25'), ('+5.50', '+5.50'), ('+5.75', '+5.75'), ('+6.00', '+6.00'), ('-0.25', '-0.25'), ('-0.50', '-0.50'), ('-0.75', '-0.75'), ('-1.00', '-1.00'), ('-1.25', '-1.25'), ('-1.50', '-1.50'), ('-1.75', '-1.75'), ('-2.00', '-2.00'), ('-2.25', '-2.25'), ('-2.50', '-2.50'), ('-2.75', '-2.75'), ('-3.00', '-3.00'), ('-3.25', '-3.25'), ('-3.50', '-3.50'), ('-3.75', '-3.75'), ('-4.00', '-4.00'), ('-4.25', '-4.25'), ('-4.50', '-4.50'), ('-4.75', '-4.75'), ('-5.00', '-5.00'), ('-5.25', '-5.25'), ('-5.50', '-5.50'), ('-5.75', '-5.75'), ('-6.00', '-6.00')], max_length=50, null=True)),
                ('axis_cylinder_re', models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130'), ('135', '135'), ('140', '140'), ('145', '145'), ('150', '150'), ('155', '155'), ('160', '160'), ('165', '165'), ('170', '170'), ('175', '175'), ('180', '180')], max_length=50, null=True)),
                ('spherical_prescription_le', models.CharField(blank=True, choices=[('0.00', '0.00'), ('+0.25', '+0.25'), ('+0.50', '+0.50'), ('+0.75', '+0.75'), ('+1.00', '+1.00'), ('+1.25', '+1.25'), ('+1.50', '+1.50'), ('+1.75', '+1.75'), ('+2.00', '+2.00'), ('+2.25', '+2.25'), ('+2.50', '+2.50'), ('+2.75', '+2.75'), ('+3.00', '+3.00'), ('+3.25', '+3.25'), ('+3.50', '+3.50'), ('+3.75', '+3.75'), ('+4.00', '+4.00'), ('+4.25', '+4.25'), ('+4.50', '+4.50'), ('+4.75', '+4.75'), ('+5.00', '+5.00'), ('+5.25', '+5.25'), ('+5.50', '+5.50'), ('+5.75', '+5.75'), ('+6.00', '+6.00'), ('+6.50', '+6.50'), ('+7.00', '+7.00'), ('+7.50', '+7.50'), ('+8.00', '+8.00'), ('+8.50', '+8.50'), ('+9.00', '+9.00'), ('+9.50', '+9.50'), ('+10.00', '+10.00'), ('+10.50', '+10.50'), ('+11.00', '+11.00'), ('+11.50', '+11.50'), ('+12.00', '+12.00'), ('+12.50', '+12.50'), ('+13.00', '+13.00'), ('+13.50', '+13.50'), ('+14.00', '+14.00'), ('+14.50', '+14.50'), ('+15.00', '+15.00'), ('+15.50', '+15.50'), ('+16.00', '+16.00'), ('+16.50', '+16.50'), ('+17.00', '+17.00'), ('+17.50', '+17.50'), ('+18.00', '+18.00'), ('+18.50', '+18.50'), ('+19.00', '+19.00'), ('+19.50', '+19.50'), ('+20.00', '+20.00'), ('-0.25', '-0.25'), ('-0.50', '-0.50'), ('-0.75', '-0.75'), ('-1.00', '-1.00'), ('-1.25', '-1.25'), ('-1.50', '-1.50'), ('-1.75', '-1.75'), ('-2.00', '-2.00'), ('-2.25', '-2.25'), ('-2.50', '-2.50'), ('-2.75', '-2.75'), ('-3.00', '-3.00'), ('-3.25', '-3.25'), ('-3.50', '-3.50'), ('-3.75', '-3.75'), ('-4.00', '-4.00'), ('-4.25', '-4.25'), ('-4.50', '-4.50'), ('-4.75', '-4.75'), ('-5.00', '-5.00'), ('-5.25', '-5.25'), ('-5.50', '-5.50'), ('-5.75', '-5.75'), ('-6.00', '-6.00'), ('-6.50', '-6.50'), ('-7.00', '-7.00'), ('-7.50', '-7.50'), ('-8.00', '-8.00'), ('-8.50', '-8.50'), ('-9.00', '-9.00'), ('-9.50', '-9.50'), ('-10.00', '-10.00'), ('-10.50', '-10.50'), ('-11.00', '-11.00'), ('-11.50', '-11.50'), ('-12.00', '-12.00'), ('-12.50', '-12.50'), ('-13.00', '-13.00'), ('-13.50', '-13.50'), ('-14.00', '-14.00'), ('-14.50', '-14.50'), ('-15.00', '-15.00'), ('-15.50', '-15.50'), ('-16.00', '-16.00'), ('-16.50', '-16.50'), ('-17.00', '-17.00'), ('-17.50', '-17.50'), ('-18.00', '-18.00'), ('-18.50', '-18.50'), ('-19.00', '-19.00'), ('-19.50', '-19.50'), ('-20.00', '-20.00')], max_length=50, null=True)),
                ('cylindrical_prescription_le', models.CharField(blank=True, choices=[('0.00', '0.00'), ('+0.25', '+0.25'), ('+0.50', '+0.50'), ('+0.75', '+0.75'), ('+1.00', '+1.00'), ('+1.25', '+1.25'), ('+1.50', '+1.50'), ('+1.75', '+1.75'), ('+2.00', '+2.00'), ('+2.25', '+2.25'), ('+2.50', '+2.50'), ('+2.75', '+2.75'), ('+3.00', '+3.00'), ('+3.25', '+3.25'), ('+3.50', '+3.50'), ('+3.75', '+3.75'), ('+4.00', '+4.00'), ('+4.25', '+4.25'), ('+4.50', '+4.50'), ('+4.75', '+4.75'), ('+5.00', '+5.00'), ('+5.25', '+5.25'), ('+5.50', '+5.50'), ('+5.75', '+5.75'), ('+6.00', '+6.00'), ('-0.25', '-0.25'), ('-0.50', '-0.50'), ('-0.75', '-0.75'), ('-1.00', '-1.00'), ('-1.25', '-1.25'), ('-1.50', '-1.50'), ('-1.75', '-1.75'), ('-2.00', '-2.00'), ('-2.25', '-2.25'), ('-2.50', '-2.50'), ('-2.75', '-2.75'), ('-3.00', '-3.00'), ('-3.25', '-3.25'), ('-3.50', '-3.50'), ('-3.75', '-3.75'), ('-4.00', '-4.00'), ('-4.25', '-4.25'), ('-4.50', '-4.50'), ('-4.75', '-4.75'), ('-5.00', '-5.00'), ('-5.25', '-5.25'), ('-5.50', '-5.50'), ('-5.75', '-5.75'), ('-6.00', '-6.00')], max_length=50, null=True)),
                ('axis_cylinder_le', models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130'), ('135', '135'), ('140', '140'), ('145', '145'), ('150', '150'), ('155', '155'), ('160', '160'), ('165', '165'), ('170', '170'), ('175', '175'), ('180', '180')], max_length=50, null=True)),
                ('refraction_spectacle_presentation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetestEyeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('test_type', models.CharField(default='Snellen E Chart', max_length=50)),
                ('test_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpectacleHistory',
            fields=[
                ('reference_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wears_spectacles', models.BooleanField(blank=True, null=True)),
                ('wearing_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('has_glasses', models.BooleanField(blank=True, null=True)),
                ('lens_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('scratched', 'Scratched'), ('dirty', 'Dirty'), ('broken', 'Broken')], max_length=20, null=True)),
                ('lens_material', models.CharField(blank=True, choices=[('glass', 'Glass'), ('plastic', 'Plastic')], max_length=10, null=True)),
                ('lens_coating', models.CharField(blank=True, choices=[('hard coat', 'Hard Coat'), ('arc', 'ARC'), ('blue coat', 'Blue Coat')], max_length=20, null=True)),
                ('lens_type', models.CharField(blank=True, choices=[('single vision', 'Single Vision'), ('bifocal', 'Bifocal'), ('multifocal', 'Multifocal'), ('lenticular', 'Lenticular')], max_length=20, null=True)),
                ('refractive_index', models.FloatField(blank=True, choices=[(1.5, '1.5'), (1.56, '1.56'), (1.67, '1.67'), (1.71, '1.71')], null=True)),
                ('frame_condition', models.CharField(blank=True, max_length=20, null=True)),
                ('frame_fit', models.BooleanField(blank=True, null=True)),
                ('frame_bent', models.BooleanField(blank=True, null=True)),
                ('frame_broken', models.BooleanField(blank=True, null=True)),
                ('frame_good_condition', models.BooleanField(blank=True, null=True)),
                ('glasses_change_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('glasses_source', models.CharField(blank=True, choices=[('eye hospital', 'Eye Hospital'), ('vision center', 'Vision Center'), ('optical store', 'Optical Store'), ('eye camp', 'Eye Camp'), ('school eye health event', 'School Eye Health Event'), ('dont know', "Don't Know"), ('other', 'Other')], max_length=50, null=True)),
                ('chose_own_frame', models.BooleanField(blank=True, null=True)),
                ('satisfaction_level', models.CharField(blank=True, choices=[('very happy', 'Very Happy'), ('happy', 'Happy'), ('ok', 'OK'), ('unhappy', 'Unhappy'), ('very unhappy', 'Very Unhappy')], max_length=20, null=True)),
                ('spectacle_wearing_history', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryTreatmentHistory',
            fields=[
                ('reference_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('surgery_done', models.BooleanField(default=False)),
                ('treated_eye', models.CharField(choices=[('Right', 'Right Eye'), ('Left', 'Left Eye'), ('Both', 'Both')], default='Both', max_length=10)),
                ('surgery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('other_surgery_details', models.CharField(blank=True, max_length=100, null=True)),
                ('left_eye_trauma', models.BooleanField(default=False)),
                ('left_eye_cataract', models.BooleanField(default=False)),
                ('left_eye_squint', models.BooleanField(default=False)),
                ('left_eye_lid', models.BooleanField(default=False)),
                ('left_eye_other', models.BooleanField(default=False)),
                ('left_eye_none', models.BooleanField(default=False)),
                ('right_eye_trauma', models.BooleanField(default=False)),
                ('right_eye_cataract', models.BooleanField(default=False)),
                ('right_eye_squint', models.BooleanField(default=False)),
                ('right_eye_lid', models.BooleanField(default=False)),
                ('right_eye_other', models.BooleanField(default=False)),
                ('right_eye_none', models.BooleanField(default=False)),
                ('surgery_treatment_history', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisualAcuityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('unaided_distance_va_re', models.CharField(blank=True, choices=[('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/6P', '6/6P'), ('6/7.5', '6/7.5'), ('6/7.5P', '6/7.5P'), ('6/9', '6/9'), ('6/9P', '6/9P'), ('6/12', '6/12'), ('6/12P', '6/12P'), ('6/18', '6/18'), ('6/18P', '6/18P'), ('6/24', '6/24'), ('6/24P', '6/24P'), ('6/36', '6/36'), ('6/36P', '6/36P'), ('6/60', '6/60'), ('5/60', '5/60'), ('4/60', '4/60'), ('3/60', '3/60'), ('2/60', '2/60'), ('1/60', '1/60'), ('FC 1/2 M', 'FC 1/2 M'), ('FCCF', 'FCCF'), ('HM(+)', 'HM(+)'), ('PL+ PR ACCURATE', 'PL+ PR ACCURATE'), ('PL + PR INACCURATE', 'PL + PR INACCURATE'), ('FIXING AND FOLLOWING LIGHT', 'FIXING AND FOLLOWING LIGHT'), ('NPL', 'NPL'), ('DEFERRED', 'DEFERRED')], max_length=50, null=True)),
                ('unaided_distance_va_le', models.CharField(blank=True, choices=[('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/6P', '6/6P'), ('6/7.5', '6/7.5'), ('6/7.5P', '6/7.5P'), ('6/9', '6/9'), ('6/9P', '6/9P'), ('6/12', '6/12'), ('6/12P', '6/12P'), ('6/18', '6/18'), ('6/18P', '6/18P'), ('6/24', '6/24'), ('6/24P', '6/24P'), ('6/36', '6/36'), ('6/36P', '6/36P'), ('6/60', '6/60'), ('5/60', '5/60'), ('4/60', '4/60'), ('3/60', '3/60'), ('2/60', '2/60'), ('1/60', '1/60'), ('FC 1/2 M', 'FC 1/2 M'), ('FCCF', 'FCCF'), ('HM(+)', 'HM(+)'), ('PL+ PR ACCURATE', 'PL+ PR ACCURATE'), ('PL + PR INACCURATE', 'PL + PR INACCURATE'), ('FIXING AND FOLLOWING LIGHT', 'FIXING AND FOLLOWING LIGHT'), ('NPL', 'NPL'), ('DEFERRED', 'DEFERRED')], max_length=50, null=True)),
                ('unaided_near_va_re', models.CharField(blank=True, choices=[('N6', 'N6'), ('N8', 'N8'), ('N10', 'N10'), ('N12', 'N12'), ('N14', 'N14'), ('N18', 'N18'), ('N24', 'N24'), ('N36', 'N36'), ('N60', 'N60'), ('LESS THEN N60', 'LESS THEN N60')], max_length=50, null=True)),
                ('unaided_near_va_le', models.CharField(blank=True, choices=[('N6', 'N6'), ('N8', 'N8'), ('N10', 'N10'), ('N12', 'N12'), ('N14', 'N14'), ('N18', 'N18'), ('N24', 'N24'), ('N36', 'N36'), ('N60', 'N60'), ('LESS THEN N60', 'LESS THEN N60')], max_length=50, null=True)),
                ('aided_distance_va_re', models.CharField(blank=True, choices=[('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/6P', '6/6P'), ('6/7.5', '6/7.5'), ('6/7.5P', '6/7.5P'), ('6/9', '6/9'), ('6/9P', '6/9P'), ('6/12', '6/12'), ('6/12P', '6/12P'), ('6/18', '6/18'), ('6/18P', '6/18P'), ('6/24', '6/24'), ('6/24P', '6/24P'), ('6/36', '6/36'), ('6/36P', '6/36P'), ('6/60', '6/60'), ('5/60', '5/60'), ('4/60', '4/60'), ('3/60', '3/60'), ('2/60', '2/60'), ('1/60', '1/60'), ('FC 1/2 M', 'FC 1/2 M'), ('FCCF', 'FCCF'), ('HM(+)', 'HM(+)'), ('PL+ PR ACCURATE', 'PL+ PR ACCURATE'), ('PL + PR INACCURATE', 'PL + PR INACCURATE'), ('FIXING AND FOLLOWING LIGHT', 'FIXING AND FOLLOWING LIGHT'), ('NPL', 'NPL'), ('DEFERRED', 'DEFERRED')], max_length=50, null=True)),
                ('aided_distance_va_le', models.CharField(blank=True, choices=[('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/6P', '6/6P'), ('6/7.5', '6/7.5'), ('6/7.5P', '6/7.5P'), ('6/9', '6/9'), ('6/9P', '6/9P'), ('6/12', '6/12'), ('6/12P', '6/12P'), ('6/18', '6/18'), ('6/18P', '6/18P'), ('6/24', '6/24'), ('6/24P', '6/24P'), ('6/36', '6/36'), ('6/36P', '6/36P'), ('6/60', '6/60'), ('5/60', '5/60'), ('4/60', '4/60'), ('3/60', '3/60'), ('2/60', '2/60'), ('1/60', '1/60'), ('FC 1/2 M', 'FC 1/2 M'), ('FCCF', 'FCCF'), ('HM(+)', 'HM(+)'), ('PL+ PR ACCURATE', 'PL+ PR ACCURATE'), ('PL + PR INACCURATE', 'PL + PR INACCURATE'), ('FIXING AND FOLLOWING LIGHT', 'FIXING AND FOLLOWING LIGHT'), ('NPL', 'NPL'), ('DEFERRED', 'DEFERRED')], max_length=50, null=True)),
                ('aided_near_va_re', models.CharField(blank=True, choices=[('N6', 'N6'), ('N8', 'N8'), ('N10', 'N10'), ('N12', 'N12'), ('N14', 'N14'), ('N18', 'N18'), ('N24', 'N24'), ('N36', 'N36'), ('N60', 'N60'), ('LESS THEN N60', 'LESS THEN N60')], max_length=50, null=True)),
                ('aided_near_va_le', models.CharField(blank=True, choices=[('N6', 'N6'), ('N8', 'N8'), ('N10', 'N10'), ('N12', 'N12'), ('N14', 'N14'), ('N18', 'N18'), ('N24', 'N24'), ('N36', 'N36'), ('N60', 'N60'), ('LESS THEN N60', 'LESS THEN N60')], max_length=50, null=True)),
                ('ph_distance_va_re', models.CharField(blank=True, choices=[('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/6P', '6/6P'), ('6/7.5', '6/7.5'), ('6/7.5P', '6/7.5P'), ('6/9', '6/9'), ('6/9P', '6/9P'), ('6/12', '6/12'), ('6/12P', '6/12P'), ('6/18', '6/18'), ('6/18P', '6/18P'), ('6/24', '6/24'), ('6/24P', '6/24P'), ('6/36', '6/36'), ('6/36P', '6/36P'), ('6/60', '6/60'), ('5/60', '5/60'), ('4/60', '4/60'), ('3/60', '3/60'), ('2/60', '2/60'), ('1/60', '1/60'), ('FC 1/2 M', 'FC 1/2 M'), ('FCCF', 'FCCF'), ('HM(+)', 'HM(+)'), ('PL+ PR ACCURATE', 'PL+ PR ACCURATE'), ('PL + PR INACCURATE', 'PL + PR INACCURATE'), ('FIXING AND FOLLOWING LIGHT', 'FIXING AND FOLLOWING LIGHT'), ('NPL', 'NPL'), ('DEFERRED', 'DEFERRED')], max_length=50, null=True)),
                ('pd_distance_va_le', models.CharField(blank=True, choices=[('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/6P', '6/6P'), ('6/7.5', '6/7.5'), ('6/7.5P', '6/7.5P'), ('6/9', '6/9'), ('6/9P', '6/9P'), ('6/12', '6/12'), ('6/12P', '6/12P'), ('6/18', '6/18'), ('6/18P', '6/18P'), ('6/24', '6/24'), ('6/24P', '6/24P'), ('6/36', '6/36'), ('6/36P', '6/36P'), ('6/60', '6/60'), ('5/60', '5/60'), ('4/60', '4/60'), ('3/60', '3/60'), ('2/60', '2/60'), ('1/60', '1/60'), ('FC 1/2 M', 'FC 1/2 M'), ('FCCF', 'FCCF'), ('HM(+)', 'HM(+)'), ('PL+ PR ACCURATE', 'PL+ PR ACCURATE'), ('PL + PR INACCURATE', 'PL + PR INACCURATE'), ('FIXING AND FOLLOWING LIGHT', 'FIXING AND FOLLOWING LIGHT'), ('NPL', 'NPL'), ('DEFERRED', 'DEFERRED')], max_length=50, null=True)),
                ('measure_visual_acuity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='Osat_app.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
    ]
