# Generated by Django 5.1.6 on 2025-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_details',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
