# Generated by Django 5.1.6 on 2025-05-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0002_school_address_school_contact_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstscreening',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='secondscreening',
            name='contact_name',
        ),
    ]
