# Generated by Django 5.1.6 on 2025-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0003_remove_firstscreening_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
