# Generated by Django 5.1.6 on 2025-05-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0004_school_country_school_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstscreening',
            name='address',
        ),
        migrations.RemoveField(
            model_name='firstscreening',
            name='country',
        ),
        migrations.RemoveField(
            model_name='firstscreening',
            name='province',
        ),
    ]
