# Generated by Django 5.1.6 on 2025-05-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0005_remove_firstscreening_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_details',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
