# Generated by Django 5.2.6 on 2025-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0006_alter_school_address_alter_school_contact_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondscreening',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
