# Generated by Django 5.2.6 on 2025-09-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0007_secondscreening_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondscreening',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secondscreening',
            name='contact_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
