# Generated by Django 5.2.6 on 2025-09-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0009_remove_firstscreening_name_participant_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='follow_up_required',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='affected_eye',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='management_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='ocular_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='refractive_error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
