# Generated by Django 5.2.6 on 2025-09-12 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0010_remove_diagnosis_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensing',
            name='glasses_dispensed',
        ),
        migrations.RemoveField(
            model_name='dispensing',
            name='glasses_ordered',
        ),
        migrations.RemoveField(
            model_name='dispensing',
            name='glasses_ready',
        ),
        migrations.RemoveField(
            model_name='dispensing',
            name='glasses_received',
        ),
        migrations.RemoveField(
            model_name='dispensing',
            name='notification_sent',
        ),
        migrations.AddField(
            model_name='dispensing',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='fitting_height_le',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='fitting_height_re',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='frame_bifocal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='frame_distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='frame_near',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='lenses_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='pd_distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='pd_near',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='provision_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='provision_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
