# Generated by Django 5.2.6 on 2025-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0011_remove_dispensing_glasses_dispensed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensing',
            name='provision_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
