# Generated by Django 5.2.6 on 2025-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0014_patientcomplaint_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomplaint',
            name='effectedEye',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
