# Generated by Django 5.2.6 on 2025-09-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0015_patientcomplaint_effectedeye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcomplaint',
            name='effectedEye',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
