# Generated by Django 5.2.6 on 2025-09-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0016_alter_patientcomplaint_effectedeye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientcomplaint',
            old_name='effectedEye',
            new_name='effected_eye',
        ),
    ]
