# Generated by Django 5.2.6 on 2025-09-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0017_rename_effectedeye_patientcomplaint_effected_eye'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomplaint',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Osat_app.participant'),
        ),
    ]
