# Generated by Django 5.2.6 on 2025-09-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0018_patientcomplaint_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomplaint',
            name='participant',
        ),
    ]
