# Generated by Django 5.2.6 on 2025-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0019_remove_patientcomplaint_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermedicalissueresponse',
            name='medical_issue',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Known', 'Not Known')], max_length=10),
        ),
    ]
