# Generated by Django 5.2.6 on 2025-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0020_alter_othermedicalissueresponse_medical_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmedicaltreatment',
            name='prescribed_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
