# Generated by Django 5.2.6 on 2025-10-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0022_refractionexamination_add_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='management_plan',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
