# Generated by Django 5.2.6 on 2025-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0023_alter_diagnosis_management_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='management_plan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
