# Generated by Django 5.2.6 on 2025-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0024_alter_diagnosis_management_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhistory',
            name='relationshipwithchild',
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Cataract_relationship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Diabetes_relationship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Glaucoma_relationship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Hypertension_relationship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Other_glasses_relationship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Other_relationship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='Other_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
