# Generated by Django 5.2.6 on 2025-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0025_remove_familyhistory_relationshipwithchild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondscreening',
            name='client_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
