# Generated by Django 5.2.6 on 2025-10-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0026_secondscreening_client_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondscreening',
            name='client_reference_number',
        ),
    ]
