# Generated by Django 5.2.6 on 2025-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0027_remove_secondscreening_client_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractionspectacle',
            name='aided_distance_va_le',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refractionspectacle',
            name='aided_distance_va_re',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refractionspectacle',
            name='aided_near_va_le',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refractionspectacle',
            name='aided_near_va_re',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
