# Generated by Django 5.2.6 on 2025-11-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0028_refractionspectacle_aided_distance_va_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensing',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensings', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='firstscreening',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_screenings', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='secondscreening',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_screenings', to='Osat_app.participant'),
        ),
    ]
