# Generated by Django 5.2.6 on 2025-11-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0030_firstscreening_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_tests', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_histories', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='initialeyetest',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_tests', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='retesteyetest',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retests', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='spectaclehistory',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery_treatments', to='Osat_app.participant'),
        ),
        migrations.AddField(
            model_name='visualacuitymeasurement',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_acuities', to='Osat_app.participant'),
        ),
    ]
