# Generated by Django 6.0.3 on 2026-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0031_comprehensiveeyetest_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='left_eye_tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='left_numeric_va',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='left_pass_fail',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='measurement_type',
            field=models.CharField(choices=[('Aided', 'Aided'), ('Unaided', 'Unaided')], default='Unaided', max_length=10),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='right_eye_tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='right_numeric_va',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='right_pass_fail',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveeyetest',
            name='testing_distance_meters',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='firstscreening',
            name='wears_spectacles',
            field=models.CharField(blank=True, choices=[('Has spectacles and is currently wearing them', 'Has spectacles and is currently wearing them'), ('Has spectacles but not wearing them', 'Has spectacles but not wearing them'), ('Spactacles not wearing', 'Spactacles not wearing'), ('Has worn spectacles in the past', 'Has worn spectacles in the past'), ('Has spectacles but not wearing and not in their possession', 'Has spectacles but not wearing and not in their possession'), ('Has previously worn spectacles but no longer has spectacles', 'Has previously worn spectacles but no longer has spectacles'), ('Has never worn spectacles before', 'Has never worn spectacles before')], max_length=255, null=True),
        ),
    ]
