# Generated by Django 6.0.3 on 2026-07-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0032_comprehensiveeyetest_left_eye_tested_and_more'),
        ('Osat_app', '0033_auto_20260716_1846'),
    ]

    operations = [
    ]
