# Generated by Django 6.0.3 on 2026-07-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0034_merge_20260721_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensing',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='fitting_height_le',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='fitting_height_re',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='frame_bifocal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='frame_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='frame_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='frame_near',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='lenses_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='pd_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='pd_near',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='provision_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispensing',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
