# Generated by Django 6.0.3 on 2026-08-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0036_alter_firstscreening_wears_spectacles'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstscreening',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firstscreening',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='firstscreening',
            name='contact_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firstscreening',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firstscreening',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firstscreening',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
