# Generated by Django 6.0.3 on 2026-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osat_app', '0037_firstscreening_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refractionexamination',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refractionexamination',
            name='eye',
            field=models.CharField(blank=True, choices=[('LEFT EYE', 'Left Eye'), ('RIGHT EYE', 'Right Eye'), ('BOTH EYES', 'Both Eyes')], max_length=10, null=True),
        ),
    ]
